// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk02twGVIHGpQutYE-EdkUHGQefPj7puk',
    appId: '1:740423556188:web:acb9e71180129b74649a99',
    messagingSenderId: '740423556188',
    projectId: 'crown-cuts-babershop',
    authDomain: 'crown-cuts-babershop.firebaseapp.com',
    storageBucket: 'crown-cuts-babershop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9AXcN8hB9i8brqpAPpFiDXvdxgfztWq0',
    appId: '1:740423556188:android:e68e67a2ca3c57ca649a99',
    messagingSenderId: '740423556188',
    projectId: 'crown-cuts-babershop',
    storageBucket: 'crown-cuts-babershop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKbvH9P5VS07tBfvq5tEkgXcXALEYwqzI',
    appId: '1:740423556188:ios:2be102826fb8654d649a99',
    messagingSenderId: '740423556188',
    projectId: 'crown-cuts-babershop',
    storageBucket: 'crown-cuts-babershop.firebasestorage.app',
    iosBundleId: 'com.crowncuts.crownCuts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKbvH9P5VS07tBfvq5tEkgXcXALEYwqzI',
    appId: '1:740423556188:ios:2be102826fb8654d649a99',
    messagingSenderId: '740423556188',
    projectId: 'crown-cuts-babershop',
    storageBucket: 'crown-cuts-babershop.firebasestorage.app',
    iosBundleId: 'com.crowncuts.crownCuts',
  );
}
